import type { AppEnv } from "../env";
import { layout, escapeHtml } from "./ui/chrome";
import { parseItem, toYaml, toXml, toJson, toAsciiBib, toIso690, slugAnchor, type RelatonItem } from "relaton";
import { parse as parsePubid } from "pubid-ts";
import { RECORD_CSS } from "./ui/record";

// Citation-formatter-style builder for a Relaton bibliographic record:
// fill in the fields, get live Relaton YAML / Relaton XML (bibdata) / JSON /
// AsciiBib output to copy — the AsciiBib form pastes straight into a
// Metanorma [bibliography] section. The form posts to /create/preview and
// all serializations are generated by relaton-ts server-side, so the page
// and the API can never drift apart.

const TYPES = [
  "standard", "article", "book", "techreport", "website",
  "software", "dataset", "presentation", "proceedings", "thesis",
  "patent", "manual", "electronic resource", "map", "misc",
];

const DATE_TYPES = ["published", "issued", "created", "updated", "accessed", "circulated"];
const ROLES = ["publisher", "author", "editor", "distributor"];

function optionList(values: string[], selected: string): string {
  return values.map((v) =>
    `<option value="${escapeHtml(v)}"${v === selected ? " selected" : ""}>${escapeHtml(v)}</option>`,
  ).join("");
}

const CSS = `
  .builder { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 32px; align-items: start; }
  @media (max-width: 980px) { .builder { grid-template-columns: minmax(0, 1fr); } }
  fieldset { border: 1px solid var(--border); border-radius: 12px; margin: 0 0 18px; padding: 14px 16px 16px; }
  legend { font-weight: 600; font-size: 14px; padding: 0 6px; }
  .fields { display: grid; grid-template-columns: 1fr 1fr; gap: 10px 12px; }
  .fields .wide { grid-column: 1 / -1; }
  label { display: flex; flex-direction: column; gap: 4px; font-size: 13px; font-weight: 500; color: var(--fg-2); }
  input, select, textarea {
    font: 14px/1.5 var(--font); padding: 8px 10px; border: 1px solid var(--border);
    border-radius: 8px; background: var(--bg); color: var(--fg); width: 100%;
  }
  textarea { font-family: var(--mono); font-size: 13px; resize: vertical; }
  input:focus, select:focus, textarea:focus { outline: 2px solid var(--accent-soft); border-color: var(--accent); }
  .row-list { display: flex; flex-direction: column; gap: 10px; }
  .row { display: grid; grid-template-columns: 1fr 1fr 1fr auto; gap: 8px; align-items: end; }
  .row .wide { grid-column: 1 / -1; }
  .btn-sm {
    font: 13px var(--font); padding: 8px 12px; border: 1px dashed var(--border);
    border-radius: 8px; background: none; color: var(--muted); cursor: pointer; align-self: end;
  }
  .btn-sm:hover { color: var(--accent); border-color: var(--accent); }
  .remove-row { font-size: 16px; line-height: 1; padding: 10px 12px; }
  .presets { display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 18px; }
  .preset {
    font: 13px var(--font); padding: 7px 14px; border: 1px solid var(--border);
    border-radius: 999px; background: var(--bg-soft); color: var(--fg-2); cursor: pointer;
  }
  .preset:hover { border-color: var(--accent); color: var(--accent); }
  .output { position: sticky; top: 87px; }
  .tabs { display: flex; gap: 2px; border-bottom: 1px solid var(--border); flex-wrap: wrap; }
  .tab-btn {
    padding: 10px 16px; font-size: 14px; font-weight: 500; font-family: var(--font);
    border: none; background: none; color: var(--muted); cursor: pointer;
    border-bottom: 2px solid transparent; margin-bottom: -1px;
  }
  .tab-btn:hover { color: var(--fg); }
  .tab-btn[aria-selected="true"] { color: var(--accent); border-bottom-color: var(--accent); }
  .panes > pre { border-radius: 0 0 8px 8px; border-top: none; max-height: 480px; overflow: auto; }
  .copy-btn { font: 13px var(--font); padding: 5px 14px; border: 1px solid var(--border); border-radius: 6px;
              background: var(--bg); color: var(--fg-2); cursor: pointer; }
  .copy-btn:hover { color: var(--accent); border-color: var(--accent); }
  .copy-btn.copied { color: var(--success); border-color: var(--success); }
  .copy-primary { background: var(--accent); border-color: var(--accent); color: #fff; }
  .copy-primary:hover { color: #fff; opacity: 0.92; }
  .output-bar { display: flex; justify-content: space-between; align-items: center; gap: 8px; padding: 6px 10px;
                background: var(--bg-soft); border: 1px solid var(--border); border-bottom: none; border-radius: 8px 8px 0 0; }
  .hint { font-size: 13px; color: var(--muted); margin: 10px 0 0; }
  .hint code { background: var(--bg-mute); padding: 2px 6px; border-radius: 4px; font-size: 12px; }
  .errors { color: #c53030; font-size: 13px; margin: 0 0 8px; }
  .fetch-card { margin: 0 0 14px; }
  .fetch-card pre { margin: 8px 0 0; }
  .cite-reading {
    margin: 8px 0 0; font-size: 15.5px; line-height: 1.6; color: var(--fg);
  }
  .pane-wrap { position: relative; }
  .pane-bar { display: flex; justify-content: flex-end; margin-bottom: -30px; padding: 6px 8px; position: relative; z-index: 2; }
  .pane-bar .copy-btn { font-size: 12px; padding: 5px 12px; background: var(--bg); }
  .fetch-head { display: flex; justify-content: space-between; align-items: center; font-size: 13px;
                font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: var(--muted); }
  .dark .errors { color: #fc8181; }
`;

const CONTRIB_ROW = `<div class="row" data-contrib-row>
  <label>Kind
    <select data-contrib-kind onchange="var r=this.closest('.row'); r.querySelector('[data-contrib-org-field]').hidden=this.value!=='organization'; r.querySelector('[data-contrib-person-field]').hidden=this.value!=='person';">
      <option value="organization">Organization</option>
      <option value="person">Person</option>
    </select>
  </label>
  <label>Role
    <select data-contrib-role>
      ${optionList(ROLES, "publisher")}
    </select>
  </label>
  <div class="wide"></div>
  <div class="wide" data-contrib-org-field><label class="wide">Organization name <input data-contrib-org placeholder="International Organization for Standardization"></label></div>
  <div class="wide" data-contrib-org-field><label>Abbreviation <input data-contrib-abbr placeholder="ISO"></label></div>
  <div class="wide" data-contrib-person-field hidden><label class="wide">Person name <input data-contrib-person placeholder="A. Bierman"></label></div>
  <button type="button" class="btn-sm remove-row" data-remove-row aria-label="Remove contributor">×</button>
</div>`;

const DATE_ROW = `<div class="row" data-date-row>
  <label>Date type
    <select data-date-type>${optionList(DATE_TYPES, "published")}</select>
  </label>
  <div></div>
  <label>Value <input data-date-value placeholder="2019-02 or 2019"></label>
  <button type="button" class="btn-sm remove-row" data-remove-row aria-label="Remove date">×</button>
</div>`;

interface PresetDef {
  label: string;
  fields: Record<string, string>;
  primary?: boolean;
  contributors: { kind: string; role: string; org?: string; person?: string }[];
  dates: { type: string; value: string }[];
}

const PRESETS: Record<string, PresetDef> = {
  iso: {
    label: "ISO standard",
    fields: {
      "f-type": "standard",
      "f-docid": "ISO 8601-1:2019",
      "f-docid-type": "ISO",
      "f-title": "Date and time — Representations for information interchange — Part 1: Basic rules",
      "f-edition": "1",
      "f-uri": "https://www.iso.org/standard/70907.html",
      "f-uri-type": "src",
      "f-language": "en",
      "f-script": "Latn",
      "f-keywords": "date, time, interchange",
    },
    primary: true,
    contributors: [
      { kind: "organization", role: "publisher", org: "International Organization for Standardization" },
      { kind: "person", role: "author", person: "A. Bierman" },
    ],
    dates: [{ type: "published", value: "2019-02" }],
  },
  rfc: {
    label: "RFC / IETF",
    fields: {
      "f-type": "standard",
      "f-docid": "RFC 8446",
      "f-docid-type": "IETF",
      "f-title": "The Transport Layer Security (TLS) Protocol Version 1.3",
      "f-uri": "https://www.rfc-editor.org/info/rfc8446",
      "f-uri-type": "src",
      "f-language": "en",
      "f-script": "Latn",
      "f-abstract": "This document specifies version 1.3 of the Transport Layer Security (TLS) protocol.",
    },
    primary: true,
    contributors: [
      { kind: "organization", role: "publisher", org: "Internet Engineering Task Force" },
      { kind: "person", role: "author", person: "E. Rescorla" },
    ],
    dates: [{ type: "published", value: "2018-08" }],
  },
  article: {
    label: "Journal article",
    fields: {
      "f-type": "article",
      "f-docid": "doi:10.1000/xyz123",
      "f-docid-type": "DOI",
      "f-title": "A study of things",
      "f-uri": "https://example.org/article",
      "f-uri-type": "src",
      "f-language": "en",
      "f-script": "Latn",
      "f-keywords": "study, things",
    },
    contributors: [
      { kind: "person", role: "author", person: "A. Author" },
      { kind: "organization", role: "publisher", org: "Example Journal" },
    ],
    dates: [{ type: "published", value: "2024-06" }],
  },
};

/** The form payload the client posts to /create/preview. */
export interface CreatePayload {
  type?: string;
  docid?: string;
  undated?: boolean;
  allParts?: boolean;
  docidType?: string;
  docidPrimary?: boolean;
  anchor?: string;
  title?: string;
  titleType?: string;
  language?: string;
  script?: string;
  edition?: string;
  uri?: string;
  uriType?: string;
  abstract?: string;
  keywords?: string[];
  contributors?: { kind: string; role: string; org?: string; abbr?: string; person?: string }[];
  dates?: { type: string; value: string }[];
}

function buildItem(p: CreatePayload): Record<string, unknown> {
  const item: Record<string, unknown> = {};
  if (p.type) item.type = p.type;
  if (p.docid) {
    const docidentifier: Record<string, unknown> = { content: p.docid };
    if (p.docidType) docidentifier.type = p.docidType;
    if (p.docidPrimary) docidentifier.primary = true;
    item.docidentifier = [docidentifier];
  }
  if (p.title) {
    const title: Record<string, unknown> = { type: p.titleType || "main", content: p.title };
    if (p.language) title.language = p.language;
    if (p.script) title.script = p.script;
    item.title = [title];
  }
  const contributors = (p.contributors ?? [])
    .map((c) => {
      const entry: Record<string, unknown> = { role: [{ type: c.role }] };
      if (c.kind === "organization") {
        if (!c.org) return null;
        const org: Record<string, unknown> = { name: [{ content: c.org }] };
        if (c.abbr) org.abbreviation = { content: c.abbr };
        entry.organization = org;
      } else {
        if (!c.person) return null;
        entry.person = { name: { completename: { content: c.person } } };
      }
      return entry;
    })
    .filter(Boolean);
  if (contributors.length) item.contributor = contributors;
  const dates = (p.dates ?? []).filter((d) => d.value).map((d) => ({ type: d.type, at: d.value }));
  if (dates.length) item.date = dates;
  if (p.edition) item.edition = { content: p.edition };
  if (p.language) item.language = [p.language];
  if (p.script) item.script = [p.script];
  if (p.uri) item.source = [{ type: p.uriType || "src", content: p.uri }];
  if (p.abstract) item.abstract = [{ content: p.abstract }];
  if (p.keywords?.length) item.keyword = p.keywords.map((k) => ({ vocab: { content: k } }));
  return item;
}

export interface PreviewResult {
  ok: boolean;
  errors?: string[];
  warnings?: string[];
  anchor?: string;
  docid?: string;
  fetchEntry?: string;
  iso690?: string;
  yaml?: string;
  xml?: string;
  json?: string;
  asciibib?: string;
}

/** Builds the item from the form payload, validates it against the
 * relaton-ts schemas, and renders every serialization server-side. */
export function renderCreatePreview(p: CreatePayload): PreviewResult {
  const item = buildItem(p);
  if (Object.keys(item).length === 0) {
    return { ok: false, errors: ["Fill in the form to generate a record."] };
  }
  const parsed = parseItem(item);
  if (!parsed.ok) {
    return { ok: false, errors: parsed.errors.map((e) => `${e.path.join(".") || "(root)"}: ${e.message}`) };
  }
  const validated = parsed.item as RelatonItem;
  const anchor = p.anchor || slugAnchor(p.docid ?? "");

  // The docid should be a PubID the relaton API can resolve — warn (not
  // fail) when pubid-ts cannot normalize it, so DOI/ISBN/custom ids still
  // build records.
  const warnings: string[] = [];
  if (p.docid && !parsePubid(p.docid)) {
    warnings.push(`"${p.docid}" is not a PubID the API recognizes — Metanorma auto-fetch will not resolve it; use the full AsciiBib block instead.`);
  }

  // The one-line fetch entry: undated resolves the latest edition at
  // build time; "(all parts)" cites the aggregate.
  let fetchDocid = p.docid ?? "";
  if (fetchDocid) {
    if (p.undated) fetchDocid = fetchDocid.replace(/:[-–]?\d{4}$/, "");
    if (p.allParts && !/all parts/i.test(fetchDocid)) {
      fetchDocid = fetchDocid.replace(/:[-–]?\d{4}$/, "").replace(/-[\d.]+$/, "") + " (all parts)";
    }
  }
  const fetchEntry = fetchDocid ? `* [[[${anchor},${fetchDocid}]]]` : "";

  return {
    ok: true,
    anchor,
    docid: fetchDocid,
    fetchEntry,
    iso690: toIso690(validated),
    warnings: warnings.length ? warnings : undefined,
    yaml: toYaml(validated),
    xml: toXml(validated),
    json: JSON.stringify(validated, null, 2),
    asciibib: toAsciiBib(validated, anchor),
  };
}

const SCRIPT = `
var TEMPLATE_CONTRIB = ${JSON.stringify(CONTRIB_ROW)};
var TEMPLATE_DATE = ${JSON.stringify(DATE_ROW)};
var PRESETS = ${JSON.stringify(PRESETS)};
var timer = null;

function el(id) { return document.getElementById(id); }
function val(id) { return (el(id).value || "").trim(); }

function readPayload() {
  var contributors = [];
  document.querySelectorAll("[data-contrib-row]").forEach(function (row) {
    var kind = row.querySelector("[data-contrib-kind]").value;
    contributors.push({
      kind: kind,
      role: row.querySelector("[data-contrib-role]").value,
      org: kind === "organization" ? row.querySelector("[data-contrib-org]").value.trim() : undefined,
      abbr: kind === "organization" ? row.querySelector("[data-contrib-abbr]").value.trim() : undefined,
      person: kind === "person" ? row.querySelector("[data-contrib-person]").value.trim() : undefined,
    });
  });
  var dates = [];
  document.querySelectorAll("[data-date-row]").forEach(function (row) {
    dates.push({
      type: row.querySelector("[data-date-type]").value,
      value: row.querySelector("[data-date-value]").value.trim(),
    });
  });
  return {
    type: val("f-type"),
    docid: val("f-docid"),
    docidType: val("f-docid-type"),
    docidPrimary: el("f-docid-primary").checked,
    undated: el("f-undated").checked,
    allParts: el("f-allparts").checked,
    anchor: val("f-anchor"),
    title: val("f-title"),
    titleType: el("f-title-type").value,
    language: val("f-language"),
    script: val("f-script"),
    edition: val("f-edition"),
    uri: val("f-uri"),
    uriType: el("f-uri-type").value,
    abstract: val("f-abstract"),
    keywords: val("f-keywords").split(",").map(function (x) { return x.trim(); }).filter(Boolean),
    contributors: contributors,
    dates: dates,
  };
}

function render(data) {
  var err = el("preview-errors");
  if (!data.ok) {
    err.textContent = (data.errors || ["Validation failed"]).join(" · ");
    err.style.display = "block";
    return;
  }
  err.style.display = "none";
  if (data.warnings && data.warnings.length) {
    err.textContent = data.warnings.join(" · ");
    err.style.display = "block";
  }
  el("out-fetch").textContent = data.fetchEntry || "";
  el("out-iso690").textContent = data.iso690 || "";
  el("out-yaml").textContent = data.yaml;
  el("out-xml").textContent = data.xml || "";
  el("out-json").textContent = data.json || "";
  el("out-asciibib").textContent = data.asciibib || "";
  el("cite-hint").innerHTML = data.anchor
    ? "Cite in Metanorma with <code>&lt;&lt;" + data.anchor + "&gt;&gt;</code> or <code>cite:[" + data.anchor + "]</code> — paste the AsciiBib block under a <code>[bibliography]</code> heading."
    : "";
}

function schedule() {
  clearTimeout(timer);
  timer = setTimeout(generate, 250);
}

async function generate() {
  try {
    var res = await fetch("/create/preview", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(readPayload()),
    });
    render(await res.json());
  } catch (e) {
    el("preview-errors").textContent = "Request failed: " + e.message;
    el("preview-errors").style.display = "block";
  }
}

function bindRowRemoval() {
  document.querySelectorAll("[data-remove-row]").forEach(function (btn) {
    if (btn.wired) return;
    btn.wired = true;
    btn.addEventListener("click", function () {
      btn.closest("[data-contrib-row], [data-date-row]").remove();
      schedule();
    });
  });
}

function applyPreset(name) {
  var p = PRESETS[name];
  if (!p) return;
  el("contrib-list").innerHTML = "";
  el("date-list").innerHTML = "";
  Object.keys(p.fields).forEach(function (id) { el(id).value = p.fields[id]; });
  el("f-docid-primary").checked = !!p.primary;
  p.contributors.forEach(function (c) {
    el("contrib-list").insertAdjacentHTML("beforeend", TEMPLATE_CONTRIB);
    var row = el("contrib-list").lastElementChild;
    row.querySelector("[data-contrib-kind]").value = c.kind;
    row.querySelector("[data-contrib-role]").value = c.role;
    if (c.kind === "organization") {
      row.querySelector("[data-contrib-org-field]").hidden = false;
      row.querySelector("[data-contrib-person-field]").hidden = true;
      row.querySelector("[data-contrib-org]").value = c.org || "";
    } else {
      row.querySelector("[data-contrib-org-field]").hidden = true;
      row.querySelector("[data-contrib-person-field]").hidden = false;
      row.querySelector("[data-contrib-person]").value = c.person || "";
    }
  });
  p.dates.forEach(function (d) {
    el("date-list").insertAdjacentHTML("beforeend", TEMPLATE_DATE);
    var row = el("date-list").lastElementChild;
    row.querySelector("[data-date-type]").value = d.type;
    row.querySelector("[data-date-value]").value = d.value;
  });
  bindRowRemoval();
  generate();
}

document.querySelectorAll("[data-preset]").forEach(function (btn) {
  btn.addEventListener("click", function () { applyPreset(btn.dataset.preset); });
});
document.querySelectorAll("input, select, textarea").forEach(function (input) {
  input.addEventListener("input", schedule);
  input.addEventListener("change", schedule);
});
el("add-contrib").addEventListener("click", function () {
  el("contrib-list").insertAdjacentHTML("beforeend", TEMPLATE_CONTRIB);
  bindRowRemoval();
  schedule();
});
el("add-date").addEventListener("click", function () {
  el("date-list").insertAdjacentHTML("beforeend", TEMPLATE_DATE);
  bindRowRemoval();
  schedule();
});
document.querySelectorAll("[data-pane-tab]").forEach(function (btn) {
  btn.addEventListener("click", function () {
    document.querySelectorAll("[data-pane-tab]").forEach(function (b) {
      b.setAttribute("aria-selected", String(b === btn));
    });
    document.querySelectorAll("[data-pane], .pane-wrap").forEach(function (p) {
      var target = p.id.replace(/^wrap-/, "pane-");
      p.hidden = target !== "pane-" + btn.dataset.paneTab;
    });
  });
});
document.querySelectorAll("[data-copy-text-source]").forEach(function (btn) {
  btn.addEventListener("click", function () {
    var src = document.getElementById(btn.dataset.copyTextSource);
    if (src && navigator.clipboard) navigator.clipboard.writeText(src.textContent || "");
    btn.textContent = "Copied!";
    setTimeout(function () { btn.textContent = "Copy"; }, 1500);
  });
});
document.querySelectorAll("[data-copy]").forEach(function (btn) {
  btn.addEventListener("click", function () {
    var pane = el("out-" + btn.dataset.copy);
    var text = pane.textContent || "";
    if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text);
    btn.textContent = "Copied!";
    btn.classList.add("copied");
    setTimeout(function () { btn.textContent = "Copy"; btn.classList.remove("copied"); }, 1500);
  });
});
generate();
`;

export function renderCreatePage(): string {
  const presets = Object.entries(PRESETS)
    .map(([key, p]) => `<button type="button" class="preset" data-preset="${key}">${escapeHtml(p.label)}</button>`)
    .join("");

  const body = `
<h1>Create a Relaton record</h1>
<p class="sub">Fill in the fields like a citation formatter — Relaton YAML, Relaton XML
(<code>bibdata</code>), JSON, and AsciiBib are generated and validated by
<a href="https://github.com/relaton/relaton-ts" rel="noopener">relaton-ts</a> as you type.
The AsciiBib output pastes straight into a Metanorma document.</p>

<div class="builder">
  <form onsubmit="return false">
    <div class="presets">
      <span class="hint" style="margin:0 8px 0 0;align-self:center">Load an example:</span>
      ${presets}
    </div>

    <fieldset>
      <legend>Identifier &amp; type</legend>
      <div class="fields">
        <label>Document identifier
          <input id="f-docid" placeholder="ISO 8601-1:2019">
        </label>
        <label>Identifier type
          <input id="f-docid-type" placeholder="ISO, IETF, DOI…">
        </label>
        <label>Type
          <select id="f-type">${optionList(TYPES, "standard")}</select>
        </label>
        <label style="justify-content:flex-end;flex-direction:row;align-items:center;gap:8px">
          <input type="checkbox" id="f-docid-primary" style="width:auto" checked> Primary identifier
        </label>
        <label class="wide">Anchor (yours to choose — default derived from the identifier)
          <input id="f-anchor" placeholder="${escapeHtml(slugAnchor("ISO 8601-1:2019"))}">
        </label>
        <label style="flex-direction:row;align-items:center;gap:8px;justify-content:flex-end">
          <input type="checkbox" id="f-undated" style="width:auto"> Undated (fetch latest edition)
        </label>
        <label style="flex-direction:row;align-items:center;gap:8px">
          <input type="checkbox" id="f-allparts" style="width:auto"> All parts (aggregate)
        </label>
      </div>
    </fieldset>

    <fieldset>
      <legend>Title</legend>
      <div class="fields">
        <label class="wide">Title
          <input id="f-title" placeholder="Date and time — Representations for information interchange">
        </label>
        <label>Title type
          <select id="f-title-type">
            <option value="main" selected>main</option>
            <option value="title-part">title-part</option>
            <option value="subtitle">subtitle</option>
          </select>
        </label>
        <label>Language
          <input id="f-language" value="en">
        </label>
        <label>Script
          <input id="f-script" value="Latn">
        </label>
      </div>
    </fieldset>

    <fieldset>
      <legend>Contributors</legend>
      <div class="row-list" id="contrib-list"></div>
      <button type="button" class="btn-sm" id="add-contrib" style="margin-top:10px">+ Add contributor</button>
    </fieldset>

    <fieldset>
      <legend>Dates</legend>
      <div class="row-list" id="date-list"></div>
      <button type="button" class="btn-sm" id="add-date" style="margin-top:10px">+ Add date</button>
    </fieldset>

    <fieldset>
      <legend>Publication details</legend>
      <div class="fields">
        <label>Edition
          <input id="f-edition" placeholder="1">
        </label>
        <label>Link type
          <select id="f-uri-type">
            <option value="src" selected>src</option>
            <option value="doi">doi</option>
            <option value="obp">obp</option>
            <option value="rss">rss</option>
          </select>
        </label>
        <label class="wide">URI
          <input id="f-uri" placeholder="https://…">
        </label>
        <label class="wide">Abstract
          <textarea id="f-abstract" rows="3"></textarea>
        </label>
        <label class="wide">Keywords (comma-separated)
          <input id="f-keywords" placeholder="date, time, interchange">
        </label>
      </div>
    </fieldset>
  </form>

  <div class="output">
    <p class="hint" style="margin:0 0 12px">relaton-ts canonical output — monospace forms are copy targets</p>
    <p class="errors" id="preview-errors" style="display:none"></p>
    <div class="fetch-card">
      <div class="fetch-head">Metanorma fetch entry <button type="button" class="copy-btn" data-copy-text-source="out-fetch">Copy</button></div>
      <pre><code id="out-fetch"></code></pre>
      <p class="hint" style="margin:6px 0 0">The anchor is yours; the identifier must be a PubID the API resolves. Undated fetches the latest edition; <em>all parts</em> cites the aggregate. To override single fields, append them under the fetch entry in AsciiBib (e.g. <code>title:: …</code>) — or expand the full block below.</p>
    </div>
    <div class="fetch-card">
      <div class="fetch-head">ISO 690 citation <button type="button" class="copy-btn" data-copy-text-source="out-iso690">Copy</button></div>
      <p class="cite-reading" id="out-iso690"></p>
    </div>
    <div class="tabs" role="tablist">
      <button class="tab-btn" data-pane-tab="yaml" role="tab" aria-selected="true">Relaton YAML</button>
      <button class="tab-btn" data-pane-tab="xml" role="tab" aria-selected="false">Relaton XML</button>
      <button class="tab-btn" data-pane-tab="json" role="tab" aria-selected="false">JSON</button>
      <button class="tab-btn" data-pane-tab="asciibib" role="tab" aria-selected="false">AsciiBib</button>
    </div>
    <div class="panes">
      <div class="pane-wrap" id="wrap-yaml"><div class="pane-bar"><button type="button" class="copy-btn" data-copy-text-source="out-yaml">Copy YAML</button></div><pre id="pane-yaml" data-pane><code id="out-yaml"></code></pre></div>
      <div class="pane-wrap" id="wrap-xml" hidden><div class="pane-bar"><button type="button" class="copy-btn" data-copy-text-source="out-xml">Copy XML</button></div><pre id="pane-xml" data-pane hidden><code id="out-xml"></code></pre></div>
      <div class="pane-wrap" id="wrap-json" hidden><div class="pane-bar"><button type="button" class="copy-btn" data-copy-text-source="out-json">Copy JSON</button></div><pre id="pane-json" data-pane hidden><code id="out-json"></code></pre></div>
      <div class="pane-wrap" id="wrap-asciibib" hidden><div class="pane-bar"><button type="button" class="copy-btn" data-copy-text-source="out-asciibib">Copy AsciiBib</button></div><pre id="pane-asciibib" data-pane hidden><code id="out-asciibib"></code></pre></div>
    </div>
    <p class="hint" id="cite-hint"></p>
  </div>
</div>`;

  return layout({ title: "Create a record — Relaton API", body: body + "<script>" + SCRIPT + "</script>", css: CSS, activeNav: "create" });
}

export type { AppEnv };
